import type { Metadata } from 'next';
import { Roboto, Rubik } from 'next/font/google';
import '../assets/styles/globals.scss';
import Providers from '@/providers/Providers';
import CustomLayout from '@/components/custom-layout/CustomLayout';
import { cookies } from 'next/headers';

const roboto = Roboto({
	subsets: ['latin', 'cyrillic'],
	weight: ['400', '500', '700'],
	variable: '--font-roboto',
	display: 'swap',
});
const rubik = Rubik({
	subsets: ['latin', 'cyrillic'],
	weight: ['400', '500', '700'],
	variable: '--font-rubik',
	display: 'swap',
});

export const metadata: Metadata = {
	title: 'Create Next App',
	description: 'Generated by create next app',
};

export default function RootLayout({
	children,
}: {
	children: React.ReactNode;
}) {
	const theme = cookies().get('theme');

	return (
		<html lang="en">
			<body
				className={`transition duration-700 ${roboto.variable} ${
					rubik.variable
				} ${theme?.value || 'lightmode'}`}
			>
				<Providers>
					<CustomLayout>{children}</CustomLayout>
				</Providers>
			</body>
		</html>
	);
}
